name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get_cppcheck
      run: sudo apt-get install cppcheck
    - name: Code Quality
      run: make analysis -C 3_Implementation
      name: make check
       run: make check
    - name: make distcheck
      run: make distcheck


